name: Mi primer CI

# trigger job on:
on: 
  push:
    branches:
      - main      # Cuando hago push a main
    tags: 
      - "v*"       # Cuando hago push con cualquier version
  pull_request:

# Jobs: Con una misma tubería de CI se pueden validar múltiples configuraciones 
# de entornos de ejecución
## Así como así corren en paralelo, se ejecutan en serie con el needs de test
jobs:
  ## Se corre para chequear código estáticamente antes de los tests
  lint: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout
      - name: Set up python
        uses: actions/setup-python@v6
        with: 
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run lint
        run: ruff check .

  test:
    # Imagen del runner
    runs-on: ubuntu-latest
    needs: lint

    # Para correr diferentes versiones de python
    strategy: 
      matrix: 
        python-version: ["3.10", "3.13"]
      
    # Acciones, una por una
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up python
        uses: actions/setup-python@v6
        with: 
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

  docker-build: 
    runs-on: ubuntu-latest
    needs: test             # to be successful

    steps:
      - name: Checkout repository
        uses: actions/checkout
      - name: Build docker image
        run: docker build -t github-actions-workshop:latest .

  # Enviar imagen a Docker Hub
  docker-push:
    runs-on: ubuntu-latest
    needs: docker-build

    if: github.event_name == 'push'   # No cuando pull request

    permissions: 
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract Docker metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-workshop
          tags: | 
            type=raw,value=latest
            type=raw,value=main
            type=ref,event=branch
            type=ref,event=tag
            type=sha
      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .      # Root directory
          push: true      # Que se mande al dockerhub
          platform: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}